# Generated by Django 5.0.4 on 2024-04-21 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapcanteen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('discount', models.IntegerField()),
                ('rating', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapcanteen.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('discount', models.IntegerField()),
                ('chefs_special', models.BooleanField()),
                ('rating', models.FloatField()),
                ('spiciness_level', models.CharField(blank=True, choices=[('Mild', 'Mild'), ('Medium', 'Medium'), ('Spicy', 'Spicy')], max_length=15, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapcanteen.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('discount', models.IntegerField()),
                ('rating', models.FloatField()),
                ('spiciness_level', models.CharField(blank=True, choices=[('Mild', 'Mild'), ('Medium', 'Medium'), ('Spicy', 'Spicy'), ('Extra Spicy', 'Extra Spicy')], max_length=15, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapcanteen.owner')),
            ],
        ),
    ]
