# Generated by Django 5.0.4 on 2024-04-23 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapcanteen', '0004_alter_cart_discount_alter_cart_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('breakfast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uapcanteen.breakfast')),
                ('dinner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uapcanteen.dinner')),
                ('lunch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uapcanteen.lunch')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapcanteen.owner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
